"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)

    op.create_table('connector_health',
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('last_success_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('last_error_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('source_name')
    )
    op.create_table('dead_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_identity', sa.String(length=64), nullable=False),
    sa.Column('loose_key', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('normalized_description_hash', sa.String(length=64), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('remote_status', sa.String(length=16), nullable=False),
    sa.Column('employment_type', sa.String(length=32), nullable=True),
    sa.Column('salary_information', sa.JSON(), nullable=True),
    sa.Column('posted_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('posted_at_reliable', sa.Boolean(), nullable=False),
    sa.Column('modified_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('closing_date', app.db.UTCDateTime(), nullable=True),
    sa.Column('company_career_url', sa.String(length=1000), nullable=True),
    sa.Column('first_discovered_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('needs_dedup_review', sa.Boolean(), nullable=False),
    sa.Column('possible_duplicate_of', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_identity')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_loose_key'), ['loose_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_normalized_title'), ['normalized_title'], unique=False)

    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('run_locks',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('external_identity', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('account_status', sa.String(length=32), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('automation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('auto_submit_consent_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('cover_letters_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_prepare_min_score', sa.Float(), nullable=False),
    sa.Column('run_interval_hours', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('report_hour_local', sa.Integer(), nullable=False),
    sa.Column('data_retention_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_data', sa.JSON(), nullable=True),
    sa.Column('verified_facts', sa.JSON(), nullable=False),
    sa.Column('work_authorization', sa.JSON(), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('validation_results', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('approved_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cover_letters_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cover_letters_user_id'), ['user_id'], unique=False)

    op.create_table('email_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('used_at', app.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('email_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_integration')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_user_id'), ['user_id'], unique=False)

    op.create_table('job_source_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('source_board', sa.String(length=200), nullable=False),
    sa.Column('source_job_id', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('application_url', sa.String(length=1000), nullable=True),
    sa.Column('source_posted_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('last_checked_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_job_id', name='uq_source_job')
    )
    with op.batch_alter_table('job_source_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_source_listings_application_url'), ['application_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_source_listings_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_source_listings_source_url'), ['source_url'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('read_at', app.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=8), nullable=False),
    sa.Column('original_file_key', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('structured_profile', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('processing_error', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_hash', name='uq_resume_user_hash')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)

    op.create_table('resume_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('generated_content', sa.JSON(), nullable=False),
    sa.Column('docx_file_key', sa.String(length=500), nullable=True),
    sa.Column('pdf_file_key', sa.String(length=500), nullable=True),
    sa.Column('validation_results', sa.JSON(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('approved_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'job_id', 'version_number', name='uq_resume_version')
    )
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_versions_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_versions_resume_id'), ['resume_id'], unique=False)

    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=200), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('match_mode', sa.String(length=16), nullable=False),
    sa.Column('exclusions', sa.JSON(), nullable=False),
    sa.Column('employment_types', sa.JSON(), nullable=False),
    sa.Column('role_preferences', sa.JSON(), nullable=False),
    sa.Column('salary_preferences', sa.JSON(), nullable=False),
    sa.Column('location_preferences', sa.JSON(), nullable=False),
    sa.Column('remote_preferences', sa.JSON(), nullable=False),
    sa.Column('other_filters', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('date_lookback_days', sa.Integer(), nullable=False),
    sa.Column('unknown_date_policy', sa.String(length=16), nullable=False),
    sa.Column('min_match_score', sa.Float(), nullable=False),
    sa.Column('overlap_hours', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resume_version_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('application_url', sa.String(length=1000), nullable=True),
    sa.Column('submission_method', sa.String(length=32), nullable=True),
    sa.Column('submission_timestamp', app.db.UTCDateTime(), nullable=True),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('manual_reason', sa.String(length=500), nullable=True),
    sa.Column('package', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', app.db.UTCDateTime(), nullable=True),
    sa.Column('approved_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cover_letter_version_id'], ['cover_letters.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_application_user_job')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)

    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('matching_factors', sa.JSON(), nullable=False),
    sa.Column('exclusion_reasons', sa.JSON(), nullable=False),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('workflow_status', sa.String(length=48), nullable=False),
    sa.Column('reported', sa.Boolean(), nullable=False),
    sa.Column('first_run_id', sa.Integer(), nullable=True),
    sa.Column('evaluated_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_profile_id'], ['search_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_profile_id', 'job_id', name='uq_match_profile_job')
    )
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_matches_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_matches_search_profile_id'), ['search_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_matches_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_match_user_qualified', ['user_id', 'qualified'], unique=False)

    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_profile_id', sa.Integer(), nullable=False),
    sa.Column('started_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('completed_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('source_statistics', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['search_profile_id'], ['search_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_runs_search_profile_id'), ['search_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_runs_user_id'), ['user_id'], unique=False)

    op.create_table('source_cursors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_profile_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('last_successful_cursor', sa.String(length=500), nullable=True),
    sa.Column('last_successful_run_at', app.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_profile_id'], ['search_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_profile_id', 'source_name', name='uq_cursor')
    )
    with op.batch_alter_table('source_cursors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_cursors_search_profile_id'), ['search_profile_id'], unique=False)

    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('previous_status', sa.String(length=48), nullable=True),
    sa.Column('new_status', sa.String(length=48), nullable=True),
    sa.Column('event_timestamp', app.db.UTCDateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_events_application_id'), ['application_id'], unique=False)

    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_profile_id', sa.Integer(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['search_profile_id'], ['search_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_run_id')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_user_id'))

    op.drop_table('daily_reports')
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_events_application_id'))

    op.drop_table('application_events')
    with op.batch_alter_table('source_cursors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_cursors_search_profile_id'))

    op.drop_table('source_cursors')
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_runs_search_profile_id'))

    op.drop_table('search_runs')
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_match_user_qualified')
        batch_op.drop_index(batch_op.f('ix_job_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_matches_search_profile_id'))
        batch_op.drop_index(batch_op.f('ix_job_matches_job_id'))

    op.drop_table('job_matches')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))

    op.drop_table('applications')
    with op.batch_alter_table('search_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_profiles_user_id'))

    op.drop_table('search_profiles')
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_versions_resume_id'))
        batch_op.drop_index(batch_op.f('ix_resume_versions_job_id'))

    op.drop_table('resume_versions')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('job_source_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_source_listings_source_url'))
        batch_op.drop_index(batch_op.f('ix_job_source_listings_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_source_listings_application_url'))

    op.drop_table('job_source_listings')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_user_id'))

    op.drop_table('integrations')
    with op.batch_alter_table('email_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_tokens_user_id'))

    op.drop_table('email_tokens')
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cover_letters_user_id'))
        batch_op.drop_index(batch_op.f('ix_cover_letters_job_id'))

    op.drop_table('cover_letters')
    op.drop_table('candidate_profiles')
    op.drop_table('automation_settings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('run_locks')
    op.drop_table('revoked_tokens')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_jobs_loose_key'))
        batch_op.drop_index(batch_op.f('ix_jobs_company_name'))

    op.drop_table('jobs')
    op.drop_table('dead_letters')
    op.drop_table('connector_health')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###