"""ai fields

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('ai_consent_at', app.db.UTCDateTime(), nullable=True))

    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rules_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_analysis', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_column('ai_analysis')
        batch_op.drop_column('rules_score')

    with op.batch_alter_table('automation_settings', schema=None) as batch_op:
        batch_op.drop_column('ai_consent_at')
        batch_op.drop_column('ai_enabled')

    # ### end Alembic commands ###