"""insights and strictness

Revision ID: 0003
Revises: 0002
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insights', sa.JSON(), nullable=True))

    with op.batch_alter_table('search_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strictness', sa.String(length=12), server_default='flexible', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_profiles', schema=None) as batch_op:
        batch_op.drop_column('strictness')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('insights')

    # ### end Alembic commands ###